### ISSUE TITLE
cannot make install / ubuntu 16.04

### ISSUE THREAD

**Issue by uuencode** [mdolidon/endlines#11]
Sorry to be a pain. I have successfully used endlines with Ubuntu 14.04, now on 16.04 it cannot compile. Here's the result of "sudo make install"

cc  -o endlines src/walkers.o src/engine.o src/main.o
src/main.o: In function `convert_one_file':
main.c:(.text+0xab5): undefined reference to`engine_run'
src/main.o: In function `check_one_file':
main.c:(.text+0xcdd): undefined reference to`engine_run'
src/main.o: In function `main':
main.c:(.text.startup+0xc9): undefined reference to`engine_run'
collect2: error: ld returned 1 exit status
makefile:10: recipe for target 'endlines' failed
make: **\* [endlines] Error 1

**Comment by mdolidon** [comment]
Hello. Your station probably doesn't have the m4 package installed : https://www.howtoinstall.co/en/ubuntu/trusty/m4

That issue may be a pretty recurrent one. I may after all revert engine.c back to a plain .c file in a while.

**Comment by uuencode** [comment]
Worked! Thank you!

**Comment by uuencode** [comment]
I was unsure if I had to open a new issue. It compiled without errors. When I try to convert  a file in a directory it says: 

endlines linux -r /mnt/DATA/test
endlines : converting files to Unix (LF)
endlines : could not restore permissions for /mnt/DATA/test/aaa.txt
endlines : could not restore ownership for /mnt/DATA/test/aaa.txt

endlines : 1 file converted from :
              - 1 Windows (CR-LF)

and the file is deleted. With "sudo" the result is the same.

Thank you in advance!

**Comment by mdolidon** [comment]
That's a new one, and might actually be an unknown and worrysome bug. I'll open a new issue for it.
