### ISSUE TITLE
Installing with yum / apt

### ISSUE THREAD

**Issue by DannyBen** [mdolidon/endlines#14]
Hey - any chance this will be available for install with yum / apt?

Its too good not to be...

**Comment by mdolidon** [comment]
Hello Danny. Thanks very much for your appreciation. This is the third time I hear that this small piece of software should be packaged. I'll look into a way to make it a Debian package, though from what I've read this may take some time, especially to find a sponsor.

**Comment by mdolidon** [comment]
Made a Debian package. That's the easy first step. However, I'm not sure to go through all the hoops and loops to get it into the distribution itself. :)

**Comment by mdolidon** [comment]
OK I'll close this issue as I know provide a Debian package. I'll spend some lost time on trying to get this into an official distribution. However it'll not be a top priority. :)
