### ISSUE TITLE
Output to STDOUT instead of STDERR

### ISSUE THREAD

**Issue by DannyBen** [mdolidon/endlines#15]
Is there any particular reason that output is written to STDERR and not STDOUT?

This gets broken:

`$ endlines check -r -v . | less`

Of course, this produces the expected result:

`$ endlines check -r -v . 2>&1 | less`

Also, on a side note, it is common to allow short flag collapsing, so I expected the below to also work:

`$ endlines check -rv .`

**Comment by mdolidon** [comment]
Hello again ! :)

Short flag collapsing has indeed been bothering me for some time, and yes I'll take the opportunity to add that cleanly.

However the choice of output streams is not so obvious and I've been quite unsure for some time about the more practical way to deal with it. 
I see `stdout` as a data stream, and `stderr` as a user information stream. This view seems obvious in the case of stream to stream conversion, like in `cat file.txt | endlines unix | wc` ; any information still gets printed on the user's console while the file content get shipped on to the next pipe. With this assumption, we can either :

- choose to stay consistent in the case of file conversions `endlines unix file.txt` : print information on `stderr` event though `stdout` is not used at all in this case.
- choose to let the user pipe information messages towards utilities such as `less`, thus print messages on `stdout`.

As I understand, you'd vote for the second option ? Such has been my feeling as well after some personal usage, but I was wondering whether anybody would see his scripts break if I did this change.

**Comment by DannyBen** [comment]
I understand. Personally, I look at STDOUT as the standard output stream, which includes communicating "normal state" to the user, and STDERR as the stream to communicate abnormal behaviors. I realize I may be a minority in such a view, but this is still how I view it and how most utilities that I use work.

I thought that `endlines` was designed to operate on files and not on piped input, so for me your second option is much more appealing.

**Comment by mdolidon** [comment]
I think it would make sense to switch as per the second option indeed.
Give me some time, opportunities to sit in front of my personal projects are few and apart, but I'll certainly implement these two improvements and deliver within a couple of weeks or little more. I'll keep the issue open in the meanwhile.

**Comment by mdolidon** [comment]
Both questions, short flags collapsing as well as use of standard ouput for non-critical messages, settled in 1.9. I'll close this issue. Feel free to open a new one if anything is unsatisfactory

Best regards.
