### ISSUE TITLE
Mac binary 1.9.2

### ISSUE THREAD

**Issue by biziclop** [mdolidon/endlines#16]
Hi, here's a binary and the test_report_1.9.1.txt, compiled under 10.11.6 (15G1611) / XCode 8.2.1:
[Archive.zip](https://github.com/mdolidon/endlines/files/1428062/Archive.zip)

**Comment by mdolidon** [comment]
Hello Biziclop. This is unexpected, and very much appreciated ! I've added your compiled binary to the repo. Thanks.

**Comment by biziclop** [comment]
Hi, new release, new Mac binary! :)  
[endlines-1.9.2-osx.zip](https://github.com/mdolidon/endlines/files/2850692/endlines-1.9.2-osx.zip)  
Compiled on macOS High Sierra.

**Comment by mdolidon** [comment]
Faithful man. Thank you ! 😃

**Comment by biziclop** [comment]
Me too! :)
