### ISSUE TITLE
(1.0) it made a .sh file non-executable

### ISSUE THREAD

**Issue by mjwach** [mdolidon/endlines#6]
I just ran this on some files.  Most are just text files but one is a shell script.  After the endlines run, I found that the shell script had had its permissions changed so that it was no longer executable.  I ran chmod +x on it and it was fine again.

**Comment by mdolidon** [comment]
Well spotted, and thank you. I'll address this issue ASAP, though I may not find a moment this week.

**Comment by mdolidon** [comment]
Found a moment after all. Shoud be fixed. Thanks again mjwach !
Best regards.
