### ISSUE TITLE
brew this!

### ISSUE THREAD

**Issue by claylo** [mdolidon/endlines#9]
Would love to be able to install/update this with [brew](http://brew.sh). Handy tool that should be spread far and wide.

I've not created a Homebrew Formula myself, which is why I'm not creating a PR ... but here's the [Homebrew Formula Cookbook](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#formula-cookbook)

Picking an example Formula at random 😀 , here's [the Formula for `dos2unix`](https://github.com/Homebrew/homebrew-core/blob/master/Formula/dos2unix.rb).

Thanks for the great tool. 👍

**Comment by mdolidon** [comment]
Hello Clay.

First of all, thanks for the good feedback. It's warmly appreciated.

A while ago I'd been thinking about brewing Endlines, checked out Homebrew's docs and guidelines, until I hit this : https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Acceptable-Formulae.md and in particular this line : 

> We frown on authors submitting their own work unless it is very popular.

I don't think that 22 stars on GitHub make a package "very popular" ! :) However I may try my luck. I'll just do a couple of very minor improvements for POSIX compliance before, and may submit a brew after that, and see if it's accepted.

**Comment by mdolidon** [comment]
Well well.. As much as I'd like to brew the thing, brew : 
- doesn't want people to submit their own software
- does not work on my old OSX 10.7

And my hardware is too old to run 10.8 and above. Therefore I'll close this issue. However, if anybody likes to write a recipe, he's more than welcome ! :)
